require 'roar/representer'
require 'roar/json'
require 'roar/json/hal'

require 'slack-invite/api/presenters/paginated_presenter'
require 'slack-invite/api/presenters/status_presenter'
require 'slack-invite/api/presenters/invitation_presenter'
require 'slack-invite/api/presenters/team_presenter'
require 'slack-invite/api/presenters/teams_presenter'
require 'slack-invite/api/presenters/root_presenter'
